name: Update static APK links after release

on:
  release:
    types: [published]

jobs:
  update-static-links:
    runs-on: ubuntu-latest

    steps:
      - name: Parse release tag to get repo and version
        id: parse
        run: |
          tag=${{ github.event.release.tag_name }}
          version=$(echo "$tag" | sed 's/.*-v//')
          repo_name=$(echo "$tag" | sed 's/-v.*//')
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} dist

      - name: Update download.html and regenerate index.html
        run: |
          REPO_NAME="${{ steps.parse.outputs.repo_name }}"
          VERSION="${{ steps.parse.outputs.version }}"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/app-release.apk"
          APP_DIR="dist/public/${REPO_NAME}"

          mkdir -p "$APP_DIR"

          # Create/Update download.html with mobile-friendly UI in one line
          DOWNLOAD_HTML='<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="refresh" content="0;url='"$RELEASE_URL"'"><title>Redirecting...</title><style>body { font-family: sans-serif; text-align: center; padding: 50px; background: #f9f9f9; } a { color: #007bff; font-weight: bold; text-decoration: none; } a:hover { text-decoration: underline; }</style></head><body><p>Download not started? <a href="'"$RELEASE_URL"'">Click here</a></p></body></html>'

          echo "$DOWNLOAD_HTML" > "$APP_DIR/download.html"

          # Generate index.html with improved UI
          echo "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>App Downloads</title><style>body { font-family: sans-serif; padding: 20px; background: #fff; } h1 { font-size: 1.5em; } ul { list-style: none; padding: 0; } li { margin: 10px 0; } a { text-decoration: none; color: #0366d6; font-weight: bold; } a:hover { text-decoration: underline; }</style></head><body><h1>Available Apps</h1><ul>" > dist/index.html

          for folder in dist/public/*; do
            [ -d "$folder" ] || continue
            app_name=$(basename "$folder")
            echo "<li><a href='public/${app_name}/download.html'>${app_name}</a></li>" >> dist/index.html
          done

          echo "</ul></body></html>" >> dist/index.html

      - name: Commit and push changes
        run: |
          cd dist
          git add .
          git commit -m "Update ${{ steps.parse.outputs.repo_name }} to v${{ steps.parse.outputs.version }}" || echo "No changes to commit"
          git push origin gh-pages
